version: '3'

services:
  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_NAME: my_wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_HOST: mysql
    ports:
      - "8080:80"
    volumes:
      - ./wordpress_data2:/var/www/html

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: my_wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./mysql_data:/var/lib/mysql

  nginx:
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
  
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: always
    expose:
      - 9100

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8081:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro


volumes:
  wordpress_data:
  mysql_data: